### PR TITLE
added proxy option to soap request using axios proxy

### PR DESCRIPTION
**Pull request by razone**
--Added config to allow the use of proxy
--Changed from axios to axios https proxy fix to allow proxy to https

### CODE REVIEW

**Comment by manuel-delaiglesia** [comment]
I am connected through a corporate proxy. When using this proxy option, I get:
```
SOAP FAIL: Error: Request failed with status code 404
e <!DOCTYPE html>
<html>
    <head>
        <title>The resource cannot be found.</title>
...
    <body bgcolor="white">

            <span><H1>Server Error in '/' Application.<hr width=100% size=1 color=silver></H1>

            <h2> <i>The resource cannot be found.</i> </h2></span>

            <font face="Arial, Helvetica, Geneva, SunSans-Regular, sans-serif ">

            <b> Description: </b>HTTP 404. The resource you are looking for (or one of its dependencies) could have been removed, had its name changed, or is temporarily unavailable. &nbsp;Please review the following URL and make sure that it is spelled correctly.
            <br><br>

            <b> Requested URL: </b>/webservice/jp/operations/staticdatatransactions.asmx<br><br>
...
```

**Comment by manuel-delaiglesia** [comment]
I am connected through a corporate proxy. When using this proxy option, I get:
```
SOAP FAIL: Error: Request failed with status code 404
e <!DOCTYPE html>
<html>
    <head>
        <title>The resource cannot be found.</title>
...
    <body bgcolor="white">

            <span><H1>Server Error in '/' Application.<hr width=100% size=1 color=silver></H1>

            <h2> <i>The resource cannot be found.</i> </h2></span>

            <font face="Arial, Helvetica, Geneva, SunSans-Regular, sans-serif ">

            <b> Description: </b>HTTP 404. The resource you are looking for (or one of its dependencies) could have been removed, had its name changed, or is temporarily unavailable. &nbsp;Please review the following URL and make sure that it is spelled correctly.
            <br><br>

            <b> Requested URL: </b>/webservice/<remaining path>.asmx<br><br>
...
```
Note that the address is partial. 
easy-soap-request version: 3.4.0

**Comment by circa10a** [comment]
Can you try version 2.5.0?

**Comment by manuel-delaiglesia** [comment]
> 
> 
> Can you try version 2.5.0? @manuel-delaiglesia

Tested using version 3.4.1 and failed.
Tested using version 2.50 also failed. When testing this version, had to move url parameter outside structure:
```
module.exports = function soapRequest(url, headers, xml, timeout = 10000, proxy = false) {
  return new Promise((resolve, reject) => {
    axios(url,{
      method: 'post',
```
to avoid this error:
SOAP FAIL: TypeError [ERR_INVALID_ARG_TYPE]: The "url" argument must be of type string. Received an instance of Object

**Comment by circa10a** [comment]
That version just uses raw function parameters where starting with v3+, an object is used

**Comment by manuel-delaiglesia** [comment]
Test success using version 4.1.3.
Was following https://stackoverflow.com/questions/62286878/cant-make-https-soap-call-through-corporate-proxy-getaddrinfo-enotfound
wich was using Axios in a wrong way

replace:
```
let httpsProxyAgent = require('https-proxy-agent');
var agent = new httpsProxyAgent({hostname:<>, port:<>, rejectUnauthorized:false});
```
with: `var proxy = {host:<>, port:<>};`

**Pull request merged**
